.\" Man Page for kylin-clock
.TH UKUI-SHUTDOWN-TIMER 1 "2021-08-04" "UKUI Desktop Environment"
.\" Please adjust this date when revising the manpage.
.\"
.SH "NAME"
\fBukui-shutdown-timer\fR \- shutdown app in UKUI Desktop Environment
.SH "SYNOPSIS"
.B ukui-shutdown-timer [OPTIONS]
.SH "DESCRIPTION"
A shutdown app in UKUI Desktop Environment
.SH "OPTIONS"
.TP
\fB\-v, \-\-version\fR
Output version information and exit.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at:
http://gitlab2.kylin.com/kylin-desktop/ukui-time-shutdown/-/issues
.SH "AUTHORS"
.SS This Manual Page has been written for the UKUI Desktop Environment by:
liuliang <liuliang@kylinos.cn> (2020)
.SH "SEE ALSO"
.SS Further information may also be available at: http://wiki.ukui-desktop.org/docs
